// src/systems/tarot/utils/cardImageLoader.ts

// Map of all card images
const CARD_IMAGES: { [key: string]: any } = {
  // Major Arcana
  '00': require('../../../../assets/images/cards/rws/00_Fool.jpg'),
  '01': require('../../../../assets/images/cards/rws/01_Magician.jpg'),
  '02': require('../../../../assets/images/cards/rws/02_High_Priestess.jpg'),
  '03': require('../../../../assets/images/cards/rws/03_Empress.jpg'),
  '04': require('../../../../assets/images/cards/rws/04_Emperor.jpg'),
  '05': require('../../../../assets/images/cards/rws/05_Hierophant.jpg'),
  '06': require('../../../../assets/images/cards/rws/06_Lovers.jpg'),
  '07': require('../../../../assets/images/cards/rws/07_Chariot.jpg'),
  '08': require('../../../../assets/images/cards/rws/08_Strength.jpg'),
  '09': require('../../../../assets/images/cards/rws/09_Hermit.jpg'),
  '10': require('../../../../assets/images/cards/rws/10_Wheel_of_Fortune.jpg'),
  '11': require('../../../../assets/images/cards/rws/11_Justice.jpg'),
  '12': require('../../../../assets/images/cards/rws/12_Hanged_Man.jpg'),
  '13': require('../../../../assets/images/cards/rws/13_Death.jpg'),
  '14': require('../../../../assets/images/cards/rws/14_Temperance.jpg'),
  '15': require('../../../../assets/images/cards/rws/15_Devil.jpg'),
  '16': require('../../../../assets/images/cards/rws/16_Tower.jpg'),
  '17': require('../../../../assets/images/cards/rws/17_Star.jpg'),
  '18': require('../../../../assets/images/cards/rws/18_Moon.jpg'),
  '19': require('../../../../assets/images/cards/rws/19_Sun.jpg'),
  '20': require('../../../../assets/images/cards/rws/20_Judgement.jpg'),
  '21': require('../../../../assets/images/cards/rws/21_World.jpg'),
  
  // Cups
  'C01': require('../../../../assets/images/cards/rws/C01_Ace_of_Cups.jpg'),
  'C02': require('../../../../assets/images/cards/rws/C02_Two_of_Cups.jpg'),
  'C03': require('../../../../assets/images/cards/rws/C03_Three_of_Cups.jpg'),
  'C04': require('../../../../assets/images/cards/rws/C04_Four_of_Cups.jpg'),
  'C05': require('../../../../assets/images/cards/rws/C05_Five_of_Cups.jpg'),
  'C06': require('../../../../assets/images/cards/rws/C06_Six_of_Cups.jpg'),
  'C07': require('../../../../assets/images/cards/rws/C07_Seven_of_Cups.jpg'),
  'C08': require('../../../../assets/images/cards/rws/C08_Eight_of_Cups.jpg'),
  'C09': require('../../../../assets/images/cards/rws/C09_Nine_of_Cups.jpg'),
  'C10': require('../../../../assets/images/cards/rws/C10_Ten_of_Cups.jpg'),
  'C11': require('../../../../assets/images/cards/rws/C11_Page_of_Cups.jpg'),
  'C12': require('../../../../assets/images/cards/rws/C12_Knight_of_Cups.jpg'),
  'C13': require('../../../../assets/images/cards/rws/C13_Queen_of_Cups.jpg'),
  'C14': require('../../../../assets/images/cards/rws/C14_King_of_Cups.jpg'),
  
  // Wands
  'W01': require('../../../../assets/images/cards/rws/W01_Ace_of_Wands.jpg'),
  'W02': require('../../../../assets/images/cards/rws/W02_Two_of_Wands.jpg'),
  'W03': require('../../../../assets/images/cards/rws/W03_Three_of_Wands.jpg'),
  'W04': require('../../../../assets/images/cards/rws/W04_Four_of_Wands.jpg'),
  'W05': require('../../../../assets/images/cards/rws/W05_Five_of_Wands.jpg'),
  'W06': require('../../../../assets/images/cards/rws/W06_Six_of_Wands.jpg'),
  'W07': require('../../../../assets/images/cards/rws/W07_Seven_of_Wands.jpg'),
  'W08': require('../../../../assets/images/cards/rws/W08_Eight_of_Wands.jpg'),
  'W09': require('../../../../assets/images/cards/rws/W09_Nine_of_Wands.jpg'),
  'W10': require('../../../../assets/images/cards/rws/W10_Ten_of_Wands.jpg'),
  'W11': require('../../../../assets/images/cards/rws/W11_Page_of_Wands.jpg'),
  'W12': require('../../../../assets/images/cards/rws/W12_Knight_of_Wands.jpg'),
  'W13': require('../../../../assets/images/cards/rws/W13_Queen_of_Wands.jpg'),
  'W14': require('../../../../assets/images/cards/rws/W14_King_of_Wands.jpg'),
  
  // Swords
  'S01': require('../../../../assets/images/cards/rws/S01_Ace_of_Swords.jpg'),
  'S02': require('../../../../assets/images/cards/rws/S02_Two_of_Swords.jpg'),
  'S03': require('../../../../assets/images/cards/rws/S03_Three_of_Swords.jpg'),
  'S04': require('../../../../assets/images/cards/rws/S04_Four_of_Swords.jpg'),
  'S05': require('../../../../assets/images/cards/rws/S05_Five_of_Swords.jpg'),
  'S06': require('../../../../assets/images/cards/rws/S06_Six_of_Swords.jpg'),
  'S07': require('../../../../assets/images/cards/rws/S07_Seven_of_Swords.jpg'),
  'S08': require('../../../../assets/images/cards/rws/S08_Eight_of_Swords.jpg'),
  'S09': require('../../../../assets/images/cards/rws/S09_Nine_of_Swords.jpg'),
  'S10': require('../../../../assets/images/cards/rws/S10_Ten_of_Swords.jpg'),
  'S11': require('../../../../assets/images/cards/rws/S11_Page_of_Swords.jpg'),
  'S12': require('../../../../assets/images/cards/rws/S12_Knight_of_Swords.jpg'),
  'S13': require('../../../../assets/images/cards/rws/S13_Queen_of_Swords.jpg'),
  'S14': require('../../../../assets/images/cards/rws/S14_King_of_Swords.jpg'),
  
  // Pentacles
  'P01': require('../../../../assets/images/cards/rws/P01_Ace_of_Pentacles.jpg'),
  'P02': require('../../../../assets/images/cards/rws/P02_Two_of_Pentacles.jpg'),
  'P03': require('../../../../assets/images/cards/rws/P03_Three_of_Pentacles.jpg'),
  'P04': require('../../../../assets/images/cards/rws/P04_Four_of_Pentacles.jpg'),
  'P05': require('../../../../assets/images/cards/rws/P05_Five_of_Pentacles.jpg'),
  'P06': require('../../../../assets/images/cards/rws/P06_Six_of_Pentacles.jpg'),
  'P07': require('../../../../assets/images/cards/rws/P07_Seven_of_Pentacles.jpg'),
  'P08': require('../../../../assets/images/cards/rws/P08_Eight_of_Pentacles.jpg'),
  'P09': require('../../../../assets/images/cards/rws/P09_Nine_of_Pentacles.jpg'),
  'P10': require('../../../../assets/images/cards/rws/P10_Ten_of_Pentacles.jpg'),
  'P11': require('../../../../assets/images/cards/rws/P11_Page_of_Pentacles.jpg'),
  'P12': require('../../../../assets/images/cards/rws/P12_Knight_of_Pentacles.jpg'),
  'P13': require('../../../../assets/images/cards/rws/P13_Queen_of_Pentacles.jpg'),
  'P14': require('../../../../assets/images/cards/rws/P14_King_of_Pentacles.jpg'),
};

export function getCardImage(code: string) {
  return CARD_IMAGES[code] || CARD_IMAGES['00']; // Fallback to Fool
}